In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np

In [1]:
my_list = [1, 2, 3, 4, 5, 6]

In [2]:
type(my_list)

list

In [7]:
np.array(my_list)

array([1, 2, 3, 4, 5, 6])

In [8]:
my_numpy_array = np.array(my_list)

In [10]:
my_numpy_array.max()

np.int64(6)

In [1]:
my_list1 = [7, 8, 9, 10 ]

In [2]:
my_list2 = [1, 2, 3, 4]

In [3]:
my_list1 + my_list2

[7, 8, 9, 10, 1, 2, 3, 4]

In [8]:
my_numpy_array1 = np.array(my_list1)

In [9]:
my_numpy_array2 = np.array(my_list2)

In [10]:
my_numpy_array1 + my_numpy_array2

array([ 8, 10, 12, 14])

In [11]:
other_array = np.array([1, 2, 3, 4, 5])

In [12]:
other_array.sum()

np.int64(15)

In [13]:
other_array.min()

np.int64(1)

In [15]:
np.random.randn(4, 4)

array([[ 0.80882178,  0.71818208, -1.00828852,  0.28900279],
       [-0.21795679,  0.11330015, -0.19519789,  1.23546631],
       [ 1.10247225, -0.19860589,  0.14995758,  1.32190677],
       [-0.36162856, -0.64314669, -0.92147246,  0.15283586]])

In [16]:
np.random.randint(4, 100, 6)

array([52, 74, 15, 79, 63, 37], dtype=int32)