In [1]:
import numpy as np

In [2]:
my_matrix = [[5, 10], [15, 20]]

In [3]:
my_matrix[0]

[5, 10]

In [4]:
my_matrix[0][1]

10

In [6]:
numpy_matrix = np.array([[5, 10], [15, 20]])

In [7]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [8]:
numpy_matrix[1][0]

np.int64(15)

In [9]:
numpy_matrix.sum()

np.int64(50)

In [10]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
np.random.random((4, 5))

array([[0.54454145, 0.54709638, 0.24714508, 0.5168757 , 0.03885137],
       [0.60528625, 0.02536996, 0.99390689, 0.45825506, 0.70471312],
       [0.02499643, 0.08661078, 0.32681686, 0.92036565, 0.12623697],
       [0.54362341, 0.64303556, 0.35569865, 0.46962966, 0.75114741]])

In [14]:
first_array = np.array([[15, 20], [25, 30]])

In [15]:
second_array = np.array([[35, 40], [45, 50]])

In [17]:
first_array + second_array

array([[50, 60],
       [70, 80]])

In [18]:
third_array = np.array([[10], [20]])

In [19]:
third_array.shape

(2, 1)

In [27]:
first_matrix = np.array([[5, 10, 20]])

In [33]:
second_matrix = np.array([[25, 30], [35, 40], [12, 15]])

In [34]:
first_matrix.shape

(1, 3)

In [35]:
second_matrix.shape

(3, 2)

In [36]:
result_matrix = first_matrix.dot(second_matrix)

In [37]:
result_matrix

array([[715, 850]])