In [16]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [17]:
import numpy as np

In [18]:
new_array = np.random.randint(1, 100, 20)

In [19]:
new_array

array([16, 92, 48, 35, 76, 57, 59, 29, 49, 62, 85, 41, 46, 96, 64, 52, 76,
       28, 94, 76], dtype=int32)

In [20]:
new_array > 20

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [21]:
new_array[new_array > 20]

array([92, 48, 35, 76, 57, 59, 29, 49, 62, 85, 41, 46, 96, 64, 52, 76, 28,
       94, 76], dtype=int32)

In [22]:
matrix_array = np.array([[5, 10, 20], [25, 30, 35], [40, 45, 50]])

In [23]:
matrix_array

array([[ 5, 10, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [24]:
matrix_array.transpose()

array([[ 5, 25, 40],
       [10, 30, 45],
       [20, 35, 50]])

In [25]:
random_array = np.random.random((6, 1))

In [26]:
random_array

array([[0.94258513],
       [0.64498311],
       [0.36065033],
       [0.13740086],
       [0.50008072],
       [0.2289174 ]])

In [29]:
random_array.reshape(2,3)

array([[0.94258513, 0.64498311, 0.36065033],
       [0.13740086, 0.50008072, 0.2289174 ]])